### ISSUE TITLE
[BUG] Services with kind `forking` hangs the starting task

### ISSUE THREAD

**Issue by sisungo** [sisungo/airup#16]
When a service is set `kind = "forking"`, starting it waits forever.

## Minimal example
```toml
[service]
type = "forking"
pid-file = "/var/run/sshd.pid"

[exec]
start = "/usr/sbin/sshd -f /etc/ssh/sshd_config"
```
Save the file as `sshd.airs`, and run `airup start --sideload sshd.airs sshd`.

## Expected Behavior
The service started successfully, and the command soon returns.

## Actual Behavior
The command would never returns. To query the service, the status is `starting`. The `sshd` process started by `Airup` keeps as a zombie process.
