### ISSUE TITLE
[BUG] The `StartService` task hangs forever when a dependency loop exists between services

### ISSUE THREAD

**Issue by sisungo** [sisungo/airup#5]
When a dependency loop exists between services, starting it will cause the tasks hang forever.

## Minimal Example
The following service is named `self`.
```toml
[service]
type = "oneshot"
dependencies = ["self"]

[exec]
start = "ls"
```

## Expected Behavior
The dependency loop is detected, automatically broken and a warning log is triggered.

## Actual Behavior
The task hangs forever.
